// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVtfr_biKDQpWQp7L6beuEzhOnV2L6wRU',
    appId: '1:177413164789:web:f49e7c33f247a35974bfbc',
    messagingSenderId: '177413164789',
    projectId: 'hestimate-438df',
    authDomain: 'hestimate-438df.firebaseapp.com',
    storageBucket: 'hestimate-438df.firebasestorage.app',
    measurementId: 'G-EHRCS66J5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi9Zx18cEwSZpHL4OdRqGy2zDVUvUOaTM',
    appId: '1:177413164789:android:ed1640235ea0c02c74bfbc',
    messagingSenderId: '177413164789',
    projectId: 'hestimate-438df',
    storageBucket: 'hestimate-438df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjLJoHqFP1JSYjtctUTKecVp1D0o2almc',
    appId: '1:177413164789:ios:0660add117c4f55174bfbc',
    messagingSenderId: '177413164789',
    projectId: 'hestimate-438df',
    storageBucket: 'hestimate-438df.firebasestorage.app',
    iosBundleId: 'com.example.hestimate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjLJoHqFP1JSYjtctUTKecVp1D0o2almc',
    appId: '1:177413164789:ios:0660add117c4f55174bfbc',
    messagingSenderId: '177413164789',
    projectId: 'hestimate-438df',
    storageBucket: 'hestimate-438df.firebasestorage.app',
    iosBundleId: 'com.example.hestimate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVtfr_biKDQpWQp7L6beuEzhOnV2L6wRU',
    appId: '1:177413164789:web:0a6eb5e01ccb16b474bfbc',
    messagingSenderId: '177413164789',
    projectId: 'hestimate-438df',
    authDomain: 'hestimate-438df.firebaseapp.com',
    storageBucket: 'hestimate-438df.firebasestorage.app',
    measurementId: 'G-YBCJHW53X4',
  );
}
